# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from async_worker import async_ffmpeg_worker_pb2 as async__worker_dot_async__ffmpeg__worker__pb2


class AsyncFFmpegStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.transcode = channel.unary_unary(
                '/AsyncFFmpeg/transcode',
                request_serializer=async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegRequest.SerializeToString,
                response_deserializer=async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegResponse.FromString,
                )


class AsyncFFmpegServicer(object):
    """Missing associated documentation comment in .proto file."""

    def transcode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncFFmpegServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'transcode': grpc.unary_unary_rpc_method_handler(
                    servicer.transcode,
                    request_deserializer=async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegRequest.FromString,
                    response_serializer=async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AsyncFFmpeg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncFFmpeg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def transcode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AsyncFFmpeg/transcode',
            async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegRequest.SerializeToString,
            async__worker_dot_async__ffmpeg__worker__pb2.AsyncFFmpegResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
