apiVersion: v1
kind: Service
metadata:
  name: async-ffmpeg-worker
  labels:
    app: async-ffmpeg-worker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: async-ffmpeg-worker
