apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gcsfuse
spec:
  selector:
      matchLabels:
        name: gcsfuse
  template:
    metadata:
      labels:
        name: gcsfuse
    spec:
      # Replace $SERVICE_ACCOUNT with service account name with GCS permissions that was configured with Workload Identity.
      # https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
      serviceAccountName: $SERVICE_ACCOUNT
      containers:
      - name: gcsfuse
        # Replace $GCLOUD_PROJECT with your project ID.
        image: gcr.io/$GCLOUD_PROJECT/gcsfuse:latest
        volumeMounts:
        - mountPath: /buckets/
          name: buckets
          mountPropagation: Bidirectional
        securityContext:
          # required for mounting FUSE
          # https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
          privileged: true
        # Replace $BUCKET_NAME with the name of the bucket to mount.
        command: ["/bin/bash", "-c", "mkdir -p /buckets/$BUCKET_NAME/ && gcsfuse -o allow_other --uid 999 --foreground $BUCKET_NAME /buckets/$BUCKET_NAME/"]
        lifecycle:
          preStop:
            exec:
              # Replace $BUCKET_NAME with the name of the bucket that was mounted.
              command: ["/bin/bash", "-c", "fusermount -u /buckets/$BUCKET_NAME/; rm -r /buckets/$BUCKET_NAME/"]
      volumes:
      - name: buckets
        hostPath:
          path: /home/buckets/
          type: DirectoryOrCreate
