# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ffmpeg_worker_pb2 as ffmpeg__worker__pb2


class FFmpegStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.transcode = channel.unary_unary(
                '/FFmpeg/transcode',
                request_serializer=ffmpeg__worker__pb2.Request.SerializeToString,
                response_deserializer=ffmpeg__worker__pb2.Log.FromString,
                )


class FFmpegServicer(object):
    """Missing associated documentation comment in .proto file"""

    def transcode(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FFmpegServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'transcode': grpc.unary_unary_rpc_method_handler(
                    servicer.transcode,
                    request_deserializer=ffmpeg__worker__pb2.Request.FromString,
                    response_serializer=ffmpeg__worker__pb2.Log.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FFmpeg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FFmpeg(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def transcode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FFmpeg/transcode',
            ffmpeg__worker__pb2.Request.SerializeToString,
            ffmpeg__worker__pb2.Log.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
