apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ffmpeg-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ffmpeg-worker
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Value
        averageValue: 1000
  minReplicas: 1
  maxReplicas: 50
