apiVersion: v1
kind: Service
metadata:
  name: ffmpeg-worker
  labels:
    app: ffmpeg-worker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  - port: 8080
    targetPort: 10000
    protocol: TCP
    name: http
  selector:
    app: ffmpeg-worker
