# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from worker import ffmpeg_worker_pb2 as worker_dot_ffmpeg__worker__pb2


class FFmpegStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.transcode = channel.unary_stream(
                '/FFmpeg/transcode',
                request_serializer=worker_dot_ffmpeg__worker__pb2.FFmpegRequest.SerializeToString,
                response_deserializer=worker_dot_ffmpeg__worker__pb2.FFmpegResponse.FromString,
                )


class FFmpegServicer(object):
    """Missing associated documentation comment in .proto file."""

    def transcode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FFmpegServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'transcode': grpc.unary_stream_rpc_method_handler(
                    servicer.transcode,
                    request_deserializer=worker_dot_ffmpeg__worker__pb2.FFmpegRequest.FromString,
                    response_serializer=worker_dot_ffmpeg__worker__pb2.FFmpegResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FFmpeg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FFmpeg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def transcode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FFmpeg/transcode',
            worker_dot_ffmpeg__worker__pb2.FFmpegRequest.SerializeToString,
            worker_dot_ffmpeg__worker__pb2.FFmpegResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
